DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS reviews;

CREATE TABLE IF NOT EXISTS reviews
(
    review_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id         BIGINT,
    username          varchar,
    title             varchar,
    content           varchar,
    created_date_time TIMESTAMP,
    updated_date_time TIMESTAMP,
    mark              INTEGER,
    event_id          BIGINT
);

CREATE TABLE IF NOT EXISTS review_likes
(
    like_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id        BIGINT  NOT NULL REFERENCES reviews (review_id) ON DELETE CASCADE,
    user_id          BIGINT  NOT NULL,
    is_like          BOOLEAN NOT NULL,
    created_datetime TIMESTAMP
);

