CREATE TABLE IF NOT EXISTS reviews
(
    review_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id         BIGINT,
    username          varchar,
    title             varchar,
    content           varchar,
    created_date_time TIMESTAMP,
    updated_date_time TIMESTAMP,
    mark              INTEGER,
    event_id          BIGINT
);