CREATE TABLE IF NOT EXISTS review_likes
(
    like_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id        BIGINT  NOT NULL REFERENCES reviews (review_id) ON DELETE CASCADE,
    user_id          BIGINT  NOT NULL,
    is_like          BOOLEAN NOT NULL,
    created_datetime TIMESTAMP
);