name: Maven Package

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Check application
        run: |
          cp -rf ./tests/checkstyle.xml ./checkstyle.xml
          cp -rf ./tests/suppressions.xml ./suppressions.xml

      - name: Build and test with Maven
        run: mvn -B package --file pom.xml
        --reporters cli,json \
        --reporter-json-export test-coverage.json

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman tests for Review Service
        run: |
          newman run postman/sprint 1 add-review-service.postman_collection.json \
          --reporters cli,json \
          --reporter-json-export results-review-service.json

      - name: Run Postman tests for Feature Likes
        run: |
          newman run postman/sprint 1 -add-review-service-and-likes-dislikes.postman_collection.json \
          --reporters cli,json \
          --reporter-json-export results-feature-likes.json

      - name: Run Postman tests for Feature Statistics
        run: |
          newman run postman/workshop sprint 1 -add-statistic.postman_collection.json \
          --reporters cli,json \
          --reporter-json-export results-feature-statistics.json

      - name: Publish results (optional)
        run: |
          echo "Review Service Results:"
          cat results-review-service.json
          echo "Feature Likes Results:"
          cat results-feature-likes.json
          echo "Feature Statistics Results:"
          cat results-feature-statistics.json